services:
  postgres:
    image: 'postgres:latest'
    container_name: 'footabll_market_db'
    environment:
      - 'POSTGRES_DB=football_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
