spring.application.name=market
spring.datasource.url=jdbc:postgresql://localhost:5432/football_db
spring.datasource.username=admin
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true


# Konfiguracja API-Football (RapidAPI)
api.football.url=https://v3.football.api-sports.io
api.football.key=bdbb4761708aedff4f87494444fcc0be